<h1><?=$title?></h1>
<style>
    #red{
        background-color:red;
    }
</style>
<h3>Table with autogenerated header</h3>
<?=$tableNoHeader?>
<h3>Table with set header</h3>
<?=$tableHeader?>
<h3>Table with set id:red</h3>
<?=$tableHeaderId?>